# Day 016 - Pandas iloc Practice

15 more iloc questions — Basic to Medium.

Format: Question cell → DataFrame cell → Empty answer cell.

## Question 1

Select rows 2, 4 and 5.

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ['Ali', 'Sara', 'John', 'David', 'Mary', 'Aisha'],
    "Department": ['Sales', 'HR', 'IT', 'Sales', 'Finance', 'HR'],
    "Salary": [50000, 45000, 70000, 60000, 55000, 48000]
})

In [4]:
df.iloc[[1,3,4]]

    Name Department  Salary
1   Sara         HR   45000
3  David      Sales   60000
4   Mary    Finance   55000

## Question 2

Select the first 3 rows and last 2 columns.

In [5]:
import pandas as pd

df = pd.DataFrame({
    "Name": ['Ali', 'Sara', 'John', 'David', 'Mary'],
    "Department": ['Sales', 'HR', 'IT', 'Sales', 'Finance'],
    "Salary": [50000, 45000, 70000, 60000, 55000],
    "City": ['Delhi', 'Mumbai', 'Pune', 'Delhi', 'Jaipur']
})

In [13]:
df.iloc[0:3,-2:]

   Salary    City
0   50000   Delhi
1   45000  Mumbai
2   70000    Pune

## Question 3

Select rows 1 through 4 and only Name and Salary.

In [14]:
import pandas as pd

df = pd.DataFrame({
    "Name": ['Ali', 'Sara', 'John', 'David', 'Mary', 'Aisha'],
    "Department": ['Sales', 'HR', 'IT', 'Sales', 'Finance', 'HR'],
    "Salary": [50000, 45000, 70000, 60000, 55000, 48000],
    "Experience": [2, 1, 4, 3, 2, 5]
})

In [36]:
df.iloc[0:4, [0,2] ]

    Name  Salary
0    Ali   50000
1   Sara   45000
2   John   70000
3  David   60000

## Question 4

Select every second row starting from the first row.

In [40]:
import pandas as pd

df = pd.DataFrame({
    "Name": ['Ali', 'Sara', 'John', 'David', 'Mary', 'Aisha'],
    "Salary": [50000, 45000, 70000, 60000, 55000, 48000]
})

In [41]:
df.iloc[:1]

  Name  Salary
0  Ali   50000

## Question 5

Select every second column starting from the first column.

In [42]:
import pandas as pd

df = pd.DataFrame({
    "Name": ['Ali', 'Sara', 'John'],
    "Department": ['Sales', 'HR', 'IT'],
    "Salary": [50000, 45000, 70000],
    "City": ['Delhi', 'Mumbai', 'Pune']
})

In [ ]:
# Write your answer here

## Question 6

Select the first row and the last column.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Name": ['Ali', 'Sara', 'John'],
    "Department": ['Sales', 'HR', 'IT'],
    "Salary": [50000, 45000, 70000],
    "City": ['Delhi', 'Mumbai', 'Pune']
})

In [ ]:
# Write your answer here

## Question 7

Select the last 3 rows.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Name": ['Ali', 'Sara', 'John', 'David', 'Mary', 'Aisha'],
    "Salary": [50000, 45000, 70000, 60000, 55000, 48000]
})

In [ ]:
# Write your answer here

## Question 8

Select the first 2 rows and first 3 columns.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Name": ['Ali', 'Sara', 'John', 'David'],
    "Department": ['Sales', 'HR', 'IT', 'Sales'],
    "Salary": [50000, 45000, 70000, 60000],
    "City": ['Delhi', 'Mumbai', 'Pune', 'Delhi']
})

In [ ]:
# Write your answer here

## Question 9

Select rows 2 to 5 and columns 1 to 3.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Name": ['Ali', 'Sara', 'John', 'David', 'Mary', 'Aisha'],
    "Department": ['Sales', 'HR', 'IT', 'Sales', 'Finance', 'HR'],
    "Salary": [50000, 45000, 70000, 60000, 55000, 48000],
    "City": ['Delhi', 'Mumbai', 'Pune', 'Delhi', 'Jaipur', 'Delhi']
})

In [ ]:
# Write your answer here

## Question 10

Select the second row as a Series.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Name": ['Ali', 'Sara', 'John'],
    "Department": ['Sales', 'HR', 'IT'],
    "Salary": [50000, 45000, 70000]
})

In [ ]:
# Write your answer here

## Question 11

Select the second column as a Series.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Name": ['Ali', 'Sara', 'John'],
    "Department": ['Sales', 'HR', 'IT'],
    "Salary": [50000, 45000, 70000]
})

In [ ]:
# Write your answer here

## Question 12

Select the last, second-last and third-last rows.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Name": ['Ali', 'Sara', 'John', 'David', 'Mary'],
    "Salary": [50000, 45000, 70000, 60000, 55000]
})

In [ ]:
# Write your answer here

## Question 13

Select rows 0, 2 and 4 with only Name and Salary.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Name": ['Ali', 'Sara', 'John', 'David', 'Mary'],
    "Department": ['Sales', 'HR', 'IT', 'Sales', 'Finance'],
    "Salary": [50000, 45000, 70000, 60000, 55000]
})

In [ ]:
# Write your answer here

## Question 14

Select the bottom 2 rows and first 2 columns.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Name": ['Ali', 'Sara', 'John', 'David', 'Mary'],
    "Department": ['Sales', 'HR', 'IT', 'Sales', 'Finance'],
    "Salary": [50000, 45000, 70000, 60000, 55000]
})

In [ ]:
# Write your answer here

## Question 15

Select rows 1, 3 and 5 and columns 0 and 2.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Name": ['Ali', 'Sara', 'John', 'David', 'Mary', 'Aisha'],
    "Department": ['Sales', 'HR', 'IT', 'Sales', 'Finance', 'HR'],
    "Salary": [50000, 45000, 70000, 60000, 55000, 48000],
    "Experience": [2, 1, 4, 3, 2, 5]
})

In [ ]:
# Write your answer here