# Day 017 - Python + Pandas Interview Practice

Topics: for loops, def/functions, list comprehension, loc, iloc.

Level: Medium | Data Analyst / Junior Data Engineer (2–3 years)

Format: Question cell → DataFrame cell → Empty answer cell.

## Question 1 — For Loop

**Task:** Print employee names whose salary is greater than 60000.

In [1]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'John', 'David'],
    'Salary': [50000, 45000, 70000, 60000]
})

In [13]:
for _,i in df.iterrows():
    if i['Salary'] > 60000:
        print(i['Name'])

John

## Question 2 — For Loop + If

**Task:** Using a loop, create a list containing salaries >= 55000.

In [14]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'John', 'David', 'Mary'],
    'Salary': [50000, 45000, 70000, 60000, 55000]
})

In [22]:
new_list = []
for i in df['Salary']:
    if i >= 55000:
        new_list.append(i)
print(new_list)

[70000, 60000, 55000]

## Question 3 — Function

**Task:** Write average_salary(df) using a loop and return the average salary.

In [27]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'John'],
    'Salary': [50000, 60000, 70000]
})

In [28]:
def average_salary(df):
    count = 0
    sum_ = 0
    for i in df['Salary']:
        count += 1
        sum_ += i
    avg_ = sum_/count
    return avg_
average_salary(df)

60000.0

## Question 4 — Function + Loop

**Task:** Write high_salary_names(df) that returns names with salary > 55000.

In [30]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'John', 'David'],
    'Salary': [50000, 45000, 70000, 60000]
})

In [36]:
def high_salary_names(df):
    for _,i in df.iterrows():
        if i['Salary'] >55000:
            return print(i['Name'],i['Salary'])
high_salary_names(df)

John 70000

## Question 5 — List Comprehension

**Task:** Using list comprehension, create a list of salaries greater than 50000.

In [39]:
import pandas as pd

df = pd.DataFrame({
    'Salary': [40000, 50000, 60000, 70000, 45000]
})

In [41]:
new_list = [i for i in df['Salary'] if i > 50000]
new_list

[60000, 70000]

## Question 6 — List Comprehension + String

**Task:** Using list comprehension, create lowercase names with spaces removed.

In [49]:
import pandas as pd

df = pd.DataFrame({
    'Name': [' Ali ', 'SARA ', ' John', 'DAVID ']
})

In [55]:
new_list = [i.strip().lower() for i in df['Name']]
new_list

['ali', 'sara', 'john', 'david']

## Question 7 — List Comprehension + Condition

**Task:** Using list comprehension, create High for salary >= 60000, otherwise Low.

In [73]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'John', 'David'],
    'Salary': [50000, 45000, 70000, 60000]
})

In [74]:
new_list = ['High' if i >= 60000 else 'LOW' for i in df['Salary']]
df["category"] = new_list
df

    Name  Salary category
0    Ali   50000      LOW
1   Sara   45000      LOW
2   John   70000     High
3  David   60000     High

## Question 8 — loc - Basic

**Task:** Using loc, select Name and Salary for employees whose salary > 55000.

In [75]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'John', 'David'],
    'Department': ['Sales', 'HR', 'IT', 'Sales'],
    'Salary': [50000, 45000, 70000, 60000]
})

In [80]:
df.loc[df['Salary']>55000,['Name','Salary']]

    Name  Salary
2   John   70000
3  David   60000

## Question 9 — loc - Multiple Conditions

**Task:** Using loc, select Sales employees whose salary >= 60000.

In [81]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'John', 'David', 'Mary'],
    'Department': ['Sales', 'HR', 'Sales', 'IT', 'Sales'],
    'Salary': [50000, 45000, 70000, 60000, 55000]
})

In [96]:
df.loc[(df['Department']=='Sales')&(df['Salary']>=60000)]

   Name Department  Salary
2  John      Sales   70000

## Question 10 — loc - Update

**Task:** Using loc, increase salary by 5000 for all Sales employees.

In [132]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'John', 'David'],
    'Department': ['Sales', 'HR', 'Sales', 'IT'],
    'Salary': [50000, 45000, 70000, 60000]
})

In [133]:
df.loc[df['Department']=='Sales','Salary']+= 5000

## Question 11 — iloc - Rows

**Task:** Using iloc, select rows 1 and 3.

In [134]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'John', 'David'],
    'Department': ['Sales', 'HR', 'IT', 'Sales'],
    'Salary': [50000, 45000, 70000, 60000]
})

In [135]:
df.iloc[[0,2]]

   Name Department  Salary
0   Ali      Sales   50000
2  John         IT   70000

## Question 12 — iloc - Rows + Columns

**Task:** Using iloc, select the first 3 rows and first 2 columns.

In [144]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'John', 'David'],
    'Department': ['Sales', 'HR', 'IT', 'Sales'],
    'Salary': [50000, 45000, 70000, 60000],
    'City': ['Delhi', 'Mumbai', 'Pune', 'Delhi']
})

In [145]:
df.iloc[:3,[0,1]]

   Name Department
0   Ali      Sales
1  Sara         HR
2  John         IT

## Question 13 — Function + loc

**Task:** Write sales_employees(df) using loc and return only Sales employees.

In [146]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'John', 'David'],
    'Department': ['Sales', 'HR', 'Sales', 'IT'],
    'Salary': [50000, 45000, 70000, 60000]
})

In [148]:
def sales_employees(df):
    return df.loc[df['Department']=='Sales']
sales_employees(df)

   Name Department  Salary
0   Ali      Sales   50000
2  John      Sales   70000

## Question 14 — Function + iloc

**Task:** Write first_three(df) using iloc and return the first 3 rows.

In [149]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'John', 'David', 'Mary'],
    'Salary': [50000, 45000, 70000, 60000, 55000]
})

In [152]:
def first_three(df):
    return df.iloc[:3]
first_three(df)

   Name  Salary
0   Ali   50000
1  Sara   45000
2  John   70000

## Question 15 — Combined Interview

**Task:** Write process_data(df) that uses a loop to create a list of employee names with salary >= 60000. Return the list.

In [164]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'John', 'David', 'Mary'],
    'Department': ['Sales', 'HR', 'Sales', 'IT', 'Finance'],
    'Salary': [50000, 45000, 70000, 60000, 55000]
})

In [165]:
def process_data(df):
    new_list = []
    for _,i in df.iterrows():
        if i["Salary"] >= 60000:
            new_list.append([i['Name'],i['Salary']])
    return new_list

process_data(df)

[['John', 70000], ['David', 60000]]