# Day 014 - Pandas loc Practice

10 more loc questions. Basic to Medium. Each question has its own DataFrame.

## Question 1: Two conditions

### Dataset
```python
df=pd.DataFrame({"Name":["Ali","Sara","John","David","Mary"],"Department":["Sales","HR","Sales","IT","HR"],"Salary":[50000,45000,70000,60000,55000]})
```

### Task
Using loc, select Sales employees with salary >= 60000.

In [4]:
import pandas as pd
df=pd.DataFrame({"Name":["Ali","Sara","John","David","Mary"],"Department":["Sales","HR","Sales","IT","HR"],"Salary":[50000,45000,70000,60000,55000]})
df.loc[(df['Department']=='Sales')&
        (df['Salary']>= 60000)]

   Name Department  Salary
2  John      Sales   70000

## Question 2: OR condition

### Dataset
```python
df=pd.DataFrame({"Name":["Ali","Sara","John","David","Mary"],"Department":["Sales","HR","IT","Sales","Finance"],"Salary":[50000,45000,70000,60000,55000]})
```

### Task
Using loc, select employees from Sales OR HR.

In [10]:
df=pd.DataFrame({"Name":["Ali","Sara","John","David","Mary"],"Department":["Sales","HR","IT","Sales","Finance"],"Salary":[50000,45000,70000,60000,55000]})
df.loc[(df['Department']=='Sales')|
        (df['Department']=="HR")]

    Name Department  Salary
0    Ali      Sales   50000
1   Sara         HR   45000
3  David      Sales   60000

## Question 3: Column range

### Dataset
```python
df=pd.DataFrame({"Name":["Ali","Sara","John"],"Department":["Sales","HR","IT"],"Salary":[50000,45000,70000],"City":["Delhi","Mumbai","Pune"]})
```

### Task
Using loc, select all rows and columns from Department through City.

In [22]:
df=pd.DataFrame({"Name":["Ali","Sara","John"],"Department":["Sales","HR","IT"],"Salary":[50000,45000,70000],"City":["Delhi","Mumbai","Pune"]})
df.loc[:,['Department','Salary',"City"]]

  Department  Salary    City
0      Sales   50000   Delhi
1         HR   45000  Mumbai
2         IT   70000    Pune

## Question 4: Rows + columns

### Dataset
```python
df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","IT","Sales"],"Salary":[50000,45000,70000,60000],"City":["Delhi","Mumbai","Pune","Delhi"]})
```

### Task
Using loc, select Sales employees and only Name, Salary, City.

In [28]:
df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","IT","Sales"],"Salary":[50000,45000,70000,60000],"City":["Delhi","Mumbai","Pune","Delhi"]})
df.loc[df['Department']=='Sales',['Name','Salary','City']]

    Name  Salary   City
0    Ali   50000  Delhi
3  David   60000  Delhi

## Question 5: Update condition

### Dataset
```python
df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","IT","Sales"],"Salary":[50000,45000,70000,60000]})
```

### Task
Using loc, increase salary by 5000 for Sales employees.

In [35]:
df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","IT","Sales"],"Salary":[50000,45000,70000,60000]})
df.loc[df['Department']=='Sales','Salary'] += 5000
df

    Name Department  Salary
0    Ali      Sales   55000
1   Sara         HR   45000
2   John         IT   70000
3  David      Sales   65000

## Question 6: Create column

### Dataset
```python
df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Salary":[50000,45000,70000,60000]})
```

### Task
Using loc, create Category: High if salary >= 60000, otherwise Low.

In [39]:
df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Salary":[50000,45000,70000,60000]})
df.loc[df["Salary"]>= 60000, 'Category'] = 'High'
df.loc[df["Salary"] < 60000, 'Category'] = 'Low'
df

    Name  Salary Category
0    Ali   50000      Low
1   Sara   45000      Low
2   John   70000     High
3  David   60000     High

## Question 7: Update two columns

### Dataset
```python
df=pd.DataFrame({"Name":["Ali","Sara","John"],"Department":["Sales","HR","Sales"],"Salary":[50000,45000,70000],"City":["Delhi","Mumbai","Pune"]})
```

### Task
Using loc, for Sales employees set City to Delhi and add 2000 to Salary.

In [45]:
df=pd.DataFrame({"Name":["Ali","Sara","John"],"Department":["Sales","HR","Sales"],"Salary":[50000,45000,70000],"City":["Delhi","Mumbai","Pune"]})
df.loc[df['Department']=='Sales' , 'City'] = 'Delhi'
df.loc[df['Department']=='Sales' , 'Salary'] += 2000
df

   Name Department  Salary    City
0   Ali      Sales   52000   Delhi
1  Sara         HR   45000  Mumbai
2  John      Sales   72000   Delhi

## Question 8: Missing values

### Dataset
```python
df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","Sales","IT"],"Manager":["Ravi",None,"Amit",None]})
```

### Task
Using loc, replace missing Manager values with Not Assigned.

In [47]:
df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","Sales","IT"],"Manager":["Ravi",None,"Amit",None]})
df.loc[df['Manager'].isna(),'Manager'] ='Not Assigned'
df

    Name Department       Manager
0    Ali      Sales          Ravi
1   Sara         HR  Not Assigned
2   John      Sales          Amit
3  David         IT  Not Assigned

## Question 9: Two conditions update

### Dataset
```python
df=pd.DataFrame({"Name":["Ali","Sara","John","David","Mary"],"Department":["Sales","HR","Sales","IT","Sales"],"Salary":[50000,45000,70000,60000,55000]})
```

### Task
Using loc, set Salary to 80000 for Sales employees whose salary >= 60000.

In [50]:
df=pd.DataFrame({"Name":["Ali","Sara","John","David","Mary"],"Department":["Sales","HR","Sales","IT","Sales"],"Salary":[50000,45000,70000,60000,55000]})
df.loc[(df['Department']=='Sales')&
        (df['Salary']>=60000) , 'Salary' ] = 80000

df

    Name Department  Salary
0    Ali      Sales   50000
1   Sara         HR   45000
2   John      Sales   80000
3  David         IT   60000
4   Mary      Sales   55000

## Question 10: Interview filtering

### Dataset
```python
df=pd.DataFrame({"Name":["Ali","Sara","John","David","Mary","Aisha"],"Department":["Sales","HR","Sales","IT","Finance","Sales"],"Salary":[50000,45000,70000,60000,55000,65000],"Experience":[2,1,4,3,2,5]})
```

### Task
Using loc, return Name, Salary, Experience for Sales employees with Experience >= 3 and Salary > 55000.

In [54]:
df=pd.DataFrame({"Name":["Ali","Sara","John","David","Mary","Aisha"],"Department":["Sales","HR","Sales","IT","Finance","Sales"],"Salary":[50000,45000,70000,60000,55000,65000],"Experience":[2,1,4,3,2,5]})
df.loc[(df['Department']== "Sales")&
        (df['Experience']>= 3) &
        (df['Salary']>55000) ,[ 'Name','Salary','Experience']]

    Name  Salary  Experience
2   John   70000           4
5  Aisha   65000           5