# Day 018
- Python + Pandas Interview Practice

20 questions | Medium level

Topics: Loop, Slicing, If/Else, List, Dictionary, Function, loc, iloc, Filtering, groupby().

Format: Question cell → DataFrame/data cell → Empty answer cell.

## Question 1 — Loop

**Task:** Print names of employees whose salary is greater than 60000.

In [24]:
d = {"Name":["Ali","Sara","John","David"]
 ,"Salary":[50000,45000,70000,60000]}

{'Name': ['Ali', 'Sara', 'John', 'David'],
 'Salary': [50000, 45000, 70000, 60000]}

In [27]:
for name , salary in zip(d['Name'],d['Salary']):
    if salary > 60000:
        print(name)

John

## Question 2 — Loop + If/Else

**Task:** Using a loop, print Pass if mark >= 40, otherwise Fail.

In [31]:
df = {"Name":["Ali","Sara","John","David"],"Marks":[75,35,62,28]}

In [52]:
for name , marks in zip(df['Name'],df['Marks']):
    if marks >= 40:
        print('pass')
    else:
        print('fail')

pass
fail
pass
fail

## Question 3 — Slicing

**Task:** From the list, return the first 4 elements.

In [53]:
numbers=[10,20,30,40,50,60,70]

In [57]:
numbers[:4]

[10, 20, 30, 40]

## Question 4 — Slicing

**Task:** From the list, return the last 3 elements using slicing.

In [59]:
cities=["Delhi","Mumbai","Pune","Chennai","Jaipur","Kolkata"]

In [75]:
cities[-3:]

['Chennai', 'Jaipur', 'Kolkata']

## Question 5 — List

**Task:** Create a new list containing only even numbers using a loop.

In [85]:
numbers=[11,20,35,42,55,60,73,80]

In [87]:
new_list = []

for i in numbers:
    if i %2==0:
        new_list.append(i)
print(new_list)

[20, 42, 60, 80]

## Question 6 — List Comprehension

**Task:** Create a list of salaries increased by 10% using list comprehension.

In [90]:
salary=[40000,50000,60000,70000]

In [96]:
new_list = [i * 1.10 for i in salary]
new_list

[44000.0, 55000.00000000001, 66000.0, 77000.0]

## Question 7 — Dictionary

**Task:** Using a loop, print each employee name and salary.

In [119]:
employees={"Ali":50000,"Sara":45000,"John":70000}

In [126]:
for name , salary in employees.items():
    print(name,salary)

Ali 50000
Sara 45000
John 70000

## Question 8 — Dictionary + If

**Task:** Print employee names whose salary is greater than 50000.

In [103]:
employees={"Ali":50000,"Sara":45000,"John":70000,"David":55000}

In [112]:
for name , salary in employees.items():
    if salary > 50000:
        print(name)

John
David

## Question 9 — Function

**Task:** Write calculate_total(numbers) that returns total using a loop. Do not use sum().

In [131]:
numbers=[100,2000,300,400]

In [132]:
def  calculate_total(numbers):
    new_list = sum(numbers)
    return new_list 
calculate_total(numbers)

2800

## Question 10 — Function + If

**Task:** Write check_salary(salary) that returns High if salary >= 60000, otherwise Low.

In [136]:
salary=500000

In [137]:
def check_salary(salary):
    if salary >= 60000:
        return 'High'
    else:
        return 'Low'

check_salary(salary)

'High'

## Question 11 — loc - Basic

**Task:** Using loc, select Name and Salary.

In [140]:
import pandas as pd

df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","IT","Sales"],"Salary":[50000,45000,70000,60000]})

In [147]:
df.loc[:,['Name','Salary']]

    Name  Salary
0    Ali   50000
1   Sara   45000
2   John   70000
3  David   60000

## Question 12 — loc - Condition

**Task:** Using loc, select Sales employees only.

In [148]:
import pandas as pd

df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","Sales","IT"],"Salary":[50000,45000,70000,60000]})

In [157]:
df[df.loc[:,'Department']=='Sales']

   Name Department  Salary
0   Ali      Sales   50000
2  John      Sales   70000

## Question 13 — loc - Multiple Conditions

**Task:** Using loc, select Sales employees with salary >= 60000.

In [160]:
import pandas as pd

df=pd.DataFrame({"Name":["Ali","Sara","John","David","Mary"],"Department":["Sales","HR","Sales","IT","Sales"],"Salary":[50000,45000,70000,60000,55000]})

In [172]:
df.loc[(df['Department']=='Sales')&(df['Salary']>=60000)]

   Name Department  Salary
2  John      Sales   70000

## Question 14 — iloc - Basic

**Task:** Using iloc, select the first 3 rows.

In [180]:
import pandas as pd

df=pd.DataFrame({"Name":["Ali","Sara","John","David","Mary"],"Salary":[50000,45000,70000,60000,55000]})

In [182]:
df.iloc[:3]

   Name  Salary
0   Ali   50000
1  Sara   45000
2  John   70000

## Question 15 — iloc - Rows + Columns

**Task:** Using iloc, select rows 1 to 3 and the first 2 columns.

In [183]:
import pandas as pd

df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","IT","Sales"],"Salary":[50000,45000,70000,60000]})

In [190]:
df.iloc[1:4,:2]

    Name Department
1   Sara         HR
2   John         IT
3  David      Sales

## Question 16 — Filtering

**Task:** Filter employees whose salary is greater than 55000.

In [191]:
import pandas as pd

df=pd.DataFrame({"Name":["Ali","Sara","John","David","Mary"],"Salary":[50000,45000,70000,60000,55000]})

In [193]:
df[df['Salary']>55000]

    Name  Salary
2   John   70000
3  David   60000

## Question 17 — Filtering + Columns

**Task:** Filter Sales employees and return only Name and Salary.

In [194]:
import pandas as pd

df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","Sales","IT"],"Salary":[50000,45000,70000,60000]})

In [196]:
df[df['Department']=='Sales'][['Name','Salary']]

   Name  Salary
0   Ali   50000
2  John   70000

## Question 18 — groupby

**Task:** Using groupby(), find total salary for each department.

In [197]:
import pandas as pd

df=pd.DataFrame({"Department":["Sales","HR","Sales","IT","HR"],"Salary":[50000,40000,70000,60000,45000]})

In [199]:
df.groupby(by = 'Department')['Salary'].sum()

Department
HR        85000
IT        60000
Sales    120000
Name: Salary, dtype: int64

## Question 19 — groupby + Mean

**Task:** Using groupby(), find average salary for each department.

In [200]:
import pandas as pd

df=pd.DataFrame({"Department":["Sales","Sales","HR","HR","IT"],"Salary":[50000,70000,45000,55000,60000]})

In [202]:
df.groupby(by ='Department')['Salary'].mean()

Department
HR       50000.0
IT       60000.0
Sales    60000.0
Name: Salary, dtype: float64

## Question 20 — Combined Interview

**Task:** Write process_sales(df) that filters Sales employees with salary >= 55000 and returns their names as a list. Use a function and loc/filtering.

In [203]:
import pandas as pd

df=pd.DataFrame({"Name":["Ali","Sara","John","David","Mary"],"Department":["Sales","HR","Sales","IT","Sales"],"Salary":[50000,45000,70000,60000,55000]})

In [218]:
def process_sales(df):
    names_emp = df.loc[
        (df['Department']=='Sales')&
        (df['Salary']>=55000)]['Name'].to_list()
    return names_emp
process_sales(df)

['John', 'Mary']

NameError: name 'names_emp' is not defined