# Day 012 - Pandas Interview Practice

Medium level | Data Analyst / Junior Data Engineer (2–3 years)

Each question has its own DataFrame. Write your solution in the blank code cell.

## Question 1: groupby() - Total Revenue

### Dataset
```python
df = pd.DataFrame({
    "Department":["Sales","HR","Sales","IT","HR"],
    "Revenue":[50000,40000,70000,60000,45000]
})
```

### Task
Using groupby(), find total Revenue for each Department.

In [5]:
import pandas as pd
df = pd.DataFrame({
    "Department":["Sales","HR","Sales","IT","HR"],
    "Revenue":[50000,40000,70000,60000,45000]
})
df.groupby(by='Department')['Revenue'].sum()

Department
HR        85000
IT        60000
Sales    120000
Name: Revenue, dtype: int64

## Question 2: groupby() - Average Salary

### Dataset
```python
df = pd.DataFrame({
    "Department":["Sales","Sales","HR","HR","IT"],
    "Salary":[50000,70000,45000,55000,60000]
})
```

### Task
Using groupby(), find average Salary for each Department.

In [7]:
df = pd.DataFrame({
    "Department":["Sales","Sales","HR","HR","IT"],
    "Salary":[50000,70000,45000,55000,60000]
})

df.groupby(by ="Department")['Salary'].mean()

Department
HR       50000.0
IT       60000.0
Sales    60000.0
Name: Salary, dtype: float64

## Question 3: agg() - Multiple Metrics

### Dataset
```python
df = pd.DataFrame({
    "Department":["Sales","Sales","HR","HR","IT"],
    "Salary":[50000,70000,45000,55000,60000]
})
```

### Task
For each Department, find minimum, maximum and average Salary using agg().

In [43]:

df = pd.DataFrame({
    "Department": ["Sales", "Sales", "HR", "HR", "IT"],
    "Salary": [50000, 70000, 45000, 55000, 60000]
})

result = df.groupby("Department")["Salary"].agg(["min", "max", "mean"])
result

              min    max     mean
Department
HR          45000  55000  50000.0
IT          60000  60000  60000.0
Sales       50000  70000  60000.0

## Question 4: value_counts()

### Dataset
```python
df = pd.DataFrame({
    "City":["Delhi","Mumbai","Delhi","Pune","Delhi","Mumbai"]
})
```

### Task
Find the number of employees from each City using value_counts().

In [10]:
df = pd.DataFrame({
    "City":["Delhi","Mumbai","Delhi","Pune","Delhi","Mumbai"]
})
df.value_counts()

City
Delhi     3
Mumbai    2
Pune      1
Name: count, dtype: int64

## Question 5: drop_duplicates()

### Dataset
```python
df = pd.DataFrame({
    "employee_id":[101,102,101,103,102],
    "name":["Ali","Sara","Ali","John","Sara"],
    "salary":[50000,45000,50000,60000,45000]
})
```

### Task
Remove duplicate records based on employee_id.

In [16]:
df = pd.DataFrame({
    "employee_id":[101,102,101,103,102],
    "name":["Ali","Sara","Ali","John","Sara"],
    "salary":[50000,45000,50000,60000,45000]
})
df.drop_duplicates(subset=['employee_id'])

   employee_id  name  salary
0          101   Ali   50000
1          102  Sara   45000
3          103  John   60000

## Question 6: loc

### Dataset
```python
df = pd.DataFrame({
    "Name":["Ali","Sara","John","David"],
    "Department":["Sales","HR","Sales","IT"],
    "Salary":[50000,45000,70000,60000]
})
```

### Task
Using loc, select Name and Salary of Sales employees whose salary is greater than 55000.

In [44]:

df = pd.DataFrame({
    "Name": ["Ali", "Sara", "John", "David"],
    "Department": ["Sales", "HR", "Sales", "IT"],
    "Salary": [50000, 45000, 70000, 60000]
})

result = df.loc[
    (df["Department"] == "Sales") & (df["Salary"] > 55000),
    ["Name", "Salary"]
]

print(result)

   Name  Salary
2  John   70000

## Question 7: iloc

### Dataset
```python
df = pd.DataFrame({
    "Name":["Ali","Sara","John","David"],
    "Department":["Sales","HR","Sales","IT"],
    "Salary":[50000,45000,70000,60000]
})
```

### Task
Using iloc, select rows 1 to 3 and the first two columns.

In [53]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Ali", "Sara", "John", "David"],
    "Department": ["Sales", "HR", "Sales", "IT"],
    "Salary": [50000, 45000, 70000, 60000]
})

result = df.iloc[1:4, 0:2]

print(result)

    Name Department
1   Sara         HR
2   John      Sales
3  David         IT

## Question 8: merge()

### Dataset
```python
employees = pd.DataFrame({
    "emp_id":[1,2,3],
    "name":["Ali","Sara","John"]
})
salary = pd.DataFrame({
    "emp_id":[1,2,3],
    "salary":[50000,45000,70000]
})
```

### Task
Merge employees and salary using emp_id.

In [34]:
employees = pd.DataFrame({
    "emp_id":[1,2,3],
    "name":["Ali","Sara","John"]
})
salary = pd.DataFrame({
    "emp_id":[1,2,3],
    "salary":[50000,45000,70000]
})
employees.merge(salary,how = "inner",on='emp_id')

   emp_id  name  salary
0       1   Ali   50000
1       2  Sara   45000
2       3  John   70000

## Question 9: concat()

### Dataset
```python
df1 = pd.DataFrame({
    "Name":["Ali","Sara"],
    "Salary":[50000,45000]
})
df2 = pd.DataFrame({
    "Name":["John","David"],
    "Salary":[70000,60000]
})
```

### Task
Combine df1 and df2 vertically using concat().

In [38]:
df1 = pd.DataFrame({
    "Name":["Ali","Sara"],
    "Salary":[50000,45000]
})
df2 = pd.DataFrame({
    "Name":["John","David"],
    "Salary":[70000,60000]
})

df = pd.concat([df1,df2],ignore_index=True)

    Name  Salary
0    Ali   50000
1   Sara   45000
2   John   70000
3  David   60000

## Question 10: apply()

### Dataset
```python
df = pd.DataFrame({
    "Name":["Ali","Sara","John"],
    "Salary":[50000,60000,70000]
})
```

### Task
Create a new bonus column where bonus is 10% of Salary using apply().

In [54]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Ali", "Sara", "John"],
    "Salary": [50000, 60000, 70000]
})

df["Bonus"] = df["Salary"].apply(lambda x: x * 0.10)

print(df)

   Name  Salary   Bonus
0   Ali   50000  5000.0
1  Sara   60000  6000.0
2  John   70000  7000.0