# Day 015 - Pandas iloc Basic Practice

10 basic iloc questions. Each question has three separate cells: Question → DataFrame → Empty answer cell.

## Question 1

Select the first row.

In [1]:
import pandas as pd

df = pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","IT","Sales"],"Salary":[50000,45000,70000,60000]})

In [2]:
df.iloc[0]

Name            Ali
Department    Sales
Salary        50000
Name: 0, dtype: object

## Question 2

Select the last row.

In [3]:
import pandas as pd

df = pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","IT","Sales"],"Salary":[50000,45000,70000,60000]})

In [6]:
df.iloc[-1]

Name          David
Department    Sales
Salary        60000
Name: 3, dtype: object

## Question 3

Select the first two rows.

In [7]:
import pandas as pd

df = pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","IT","Sales"],"Salary":[50000,45000,70000,60000]})

In [11]:
df.iloc[0:2]

   Name Department  Salary
0   Ali      Sales   50000
1  Sara         HR   45000

## Question 4

Select rows 2 and 3.

In [12]:
import pandas as pd

df = pd.DataFrame({"Name":["Ali","Sara","John","David","Mary"],"Department":["Sales","HR","IT","Sales","Finance"],"Salary":[50000,45000,70000,60000,55000]})

In [20]:
df.iloc[[1,2]]

   Name Department  Salary
1  Sara         HR   45000
2  John         IT   70000

## Question 5

Select the first column.

In [21]:
import pandas as pd

df = pd.DataFrame({"Name":["Ali","Sara","John"],"Department":["Sales","HR","IT"],"Salary":[50000,45000,70000]})

In [23]:
df.iloc[:,[0]]

   Name
0   Ali
1  Sara
2  John

## Question 6

Select the first two columns.

In [24]:
import pandas as pd

df = pd.DataFrame({"Name":["Ali","Sara","John"],"Department":["Sales","HR","IT"],"Salary":[50000,45000,70000]})

In [32]:
df.iloc[:,[0,1]]

   Name Department
0   Ali      Sales
1  Sara         HR
2  John         IT

## Question 7

Select rows 1 to 3 and columns 0 to 1.

In [41]:
import pandas as pd

df = pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","IT","Sales"],"Salary":[50000,45000,70000,60000]})

In [43]:
df.iloc[1:4, 0:2]

    Name Department
1   Sara         HR
2   John         IT
3  David      Sales

## Question 8

Select only the Salary value from the third row.

In [44]:
import pandas as pd

df = pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","IT","Sales"],"Salary":[50000,45000,70000,60000]})

In [45]:
df.iloc[2,[2]]

Salary    70000
Name: 2, dtype: int64

## Question 9

Select the last two rows and the last two columns.

In [49]:
import pandas as pd

df = pd.DataFrame({"Name":["Ali","Sara","John","David","Mary"],"Department":["Sales","HR","IT","Sales","Finance"],"Salary":[50000,45000,70000,60000,55000],"City":["Delhi","Mumbai","Pune","Delhi","Jaipur"]})

In [73]:
df.iloc[-2:,-2:]

  Department  Salary
3      Sales   60000
4    Finance   55000

## Question 10

Select rows 1, 3 and 4 with all columns.

In [59]:
import pandas as pd

df = pd.DataFrame({"Name":["Ali","Sara","John","David","Mary"],"Department":["Sales","HR","IT","Sales","Finance"],"Salary":[50000,45000,70000,60000,55000]})

In [70]:
df.iloc[0:3,:]

   Name Department  Salary
0   Ali      Sales   50000
1  Sara         HR   45000
2  John         IT   70000